### ISSUE TITLE
Cannot find module Error

### ISSUE THREAD

**Issue by kazupon** [power-assert-js/webpack-espower-loader#2]
When i was  using `power-assert@0.11.0` in my develop environment (`dev/latest_test` branch on https://github.com/vuejs/vue-validator), Occurred `Error: Cannot find module` Error.

Please see the detail error log:
https://gist.github.com/kazupon/0664c72c0a4ec4513c9d

BTW, When i was  using `power-assert@0.10.2`, it works.

What I'm doing wrong?
Thanks!

**Comment by twada** [comment]
Hi @kazupon, Thank you for reporting!

This error is caused by webpack, since webpack does not support `require('./path/to/json')` by default. (In this case `estraverse` requires its package.json)

To solve this issue, you can use [webpack/json-loader](https://github.com/webpack/json-loader) by using `--module-bind json` or `module.loaders: [{test: /\.json$/, loader: "json"}]`

See also:
- [Module parse failed · Issue #303](https://github.com/webpack/webpack/issues/303)
- [webpack can't parse the webpack module · Issue #184](https://github.com/webpack/webpack/issues/184)

**Comment by kazupon** [comment]
@twada 
Thank you for quick reply.

I solved this issue.
Thanks !!
