### ISSUE TITLE
Cannot show descriptive assertion messages

### ISSUE THREAD

**Issue by kazupon** [power-assert-js/webpack-espower-loader#4]
When i was using `webpack-espower-loader` in my environment (https://github.com/kazupon/vue-plugin-boilerplate), it's works. 
However When the test was failed, `power-assert` cannot show the descriptive assertion messages.

Please see the detail error log (karma reporter: progress):
https://gist.github.com/kazupon/3ceabbe4cac1b703aa17

I become curious about the following warning messages has been output.

```
WARNING in ./~/power-assert/~/power-assert-formatter/lib/create.js
Critical dependencies:
```

What I'm doing wrong?

Thanks!

**Comment by twada** [comment]
Hi @kazupon, thank you for reporting.

To write tests in ES6 with Babel, please use [babel-plugin-espower](https://github.com/power-assert-js/babel-plugin-espower) or [espower-babel](https://github.com/power-assert-js/espower-babel) (espower-babel uses babel-plugin-espower internally).

webpack-espower-loader (and the other instrumentors) transforms code **after** babel, which does not work since babel's output has changed.

babel-plugin-espower works as a babel plugin and runs **before** babel's transformation, so it works as expected.

FYI: [I made a pull-req for you](https://github.com/kazupon/vue-plugin-boilerplate/pull/1)

Warning from webpack is due to [the use of a dynamic require](https://github.com/power-assert-js/power-assert-formatter/blob/47532a147a2b28bdf47103d53beca1c4b3c6a3c7/lib/create.js#L30) (which is [inevitable hack](https://github.com/power-assert-js/power-assert-formatter/blob/47532a147a2b28bdf47103d53beca1c4b3c6a3c7/lib/create.js#L13-L20) for plugin system) and is not really an issue, just a warning. Please ignore it though you may feel uncomfortable with.

**Comment by kazupon** [comment]
I confirmed that it works.
Thanks !! :100:

**Comment by twada** [comment]
Thank you for reporting! :+1: 
Also noticed that this should be in power-assert FAQ.

**Comment by kazupon** [comment]
Awesome !! :+1: 
That would be great for everyone.
